// src/widgets/vue/Counter.vue
<template>
  <div class="vue-counter">
    <div class="counter-display">{{ count }}</div>
    <div class="counter-buttons">
      <button class="counter-btn" @click="count--">−</button>
      <button class="counter-btn" @click="count++">+</button>
      <button class="counter-btn reset" @click="count = 0">Reset</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const count = ref<number>(0)
</script>

<style scoped>
.vue-counter {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
</style>

// src/widgets/svelte/Counter.svelte
<script>
  let count = 0

  function increment() {
    count++
  }

  function decrement() {
    count--
  }

  function reset() {
    count = 0
  }
</script>

<div class="svelte-counter">
  <div class="counter-display">{count}</div>
  <div class="counter-buttons">
    <button class="counter-btn" on:click={decrement}>−</button>
    <button class="counter-btn" on:click={increment}>+</button>
    <button class="counter-btn reset" on:click={reset}>Reset</button>
  </div>
</div>

<style>
  .svelte-counter {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
</style>
