// src/widgets/vue/Counter.vue
<template>
  <div class="vue-counter">
    <div class="counter-display">{{ count }}</div>
    <div class="counter-buttons">
      <button class="counter-btn" @click="count--">−</button>
      <button class="counter-btn" @click="count++">+</button>
      <button class="counter-btn reset" @click="count = 0">Reset</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const count = ref<number>(0)

const resetHandler = () => {
  count.value = 0
}

onMounted(() => window.addEventListener('reset-widgets', resetHandler as EventListener))
onUnmounted(() => window.removeEventListener('reset-widgets', resetHandler as EventListener))
</script>

<style scoped>
.vue-counter {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
</style>

// src/widgets/react/Counter.tsx
import React, { useState, useEffect } from 'react'

export default function Counter(): JSX.Element {
  const [count, setCount] = useState<number>(0)

  useEffect(() => {
    const handler = () => setCount(0)
    window.addEventListener('reset-widgets', handler as EventListener)
    return () => window.removeEventListener('reset-widgets', handler as EventListener)
  }, [])

  return (
    <div className="react-counter">
      <div className="counter-display">{count}</div>
      <div className="counter-buttons">
        <button className="counter-btn" onClick={() => setCount(c => c - 1)}>
          −
        </button>
        <button className="counter-btn" onClick={() => setCount(c => c + 1)}>
          +
        </button>
        <button className="counter-btn reset" onClick={() => setCount(0)}>
          Reset
        </button>
      </div>
    </div>
  )
}
